### ISSUE TITLE
question about enable_bias=True; would enable_bias influence inference?

### ISSUE THREAD

**Issue by cizhouyu** [xue-pai/SimpleX#1]
when i use the config```embedding_dim: 64;enable_bias=True ``` and print user and item embedding size in inference, i found that embedding size=65. Would enable_bias influence inference?
![issue](https://user-images.githubusercontent.com/60316519/225258315-2131ae9a-c976-4d50-b57b-e75bf0836321.png)

**Comment by zhujiem** [comment]
The bias should also be used during inference. For example, given item bias ib, the dot will be [user_vec, 1] \dot [item_vec, ib]

**Comment by zhujiem** [comment]
See https://github.com/xue-pai/SimpleX/blob/main/src/SimpleX.py#L101

**Comment by cizhouyu** [comment]
ok, thanks!
