### ISSUE TITLE
Can't import FeatureEncoder in recbox.matching.features

### ISSUE THREAD

**Issue by duanhx1037** [xue-pai/SimpleX#2]
In ```run_expid.py```, it should import ```FeatureEncoder``` in this line```from recbox.matching.features import FeatureMap, FeatureEncoder```. But it seems I can only find FeatureMap in    [recbox.matching.features.py](https://github.com/xue-pai/RecBox/blob/main/recbox/matching/features.py). Where is the **FeatureEncoder** module? Thanks.

**Comment by xpai** [comment]
Please use recbox==0.0.4

**Comment by duanhx1037** [comment]
It's ok now, thanks~
